const assert = require("node:assert/strict");
global.window = {};
require("../assets/image-edit.js");
const editor = window.QwenImageEditor;
const prefix = "image_edit/Qwen-Image-Edit-2511";
const names = ["model/model_index.json", "model/transformer/config.json", "model/text_encoder/config.json", "model/vae/config.json", "model/tokenizer/tokenizer_config.json", "model/scheduler/scheduler_config.json", "model/processor/preprocessor_config.json", "model/transformer/model.safetensors", "model/text_encoder/model.safetensors", "model/vae/model.safetensors"];
const model = { id: "qwen_image_edit_2511", packagePath: prefix, manifestFiles: names.map((name,i)=>({id:`fixture-${i}`, name:name.split("/").pop(), relativePath:prefix+"/"+name, size:"100"})) };
assert.equal(editor.manifestState(model).ready, true);
assert.equal(editor.manifestState({...model,manifestFiles:model.manifestFiles.filter(f=>!f.relativePath.includes("processor/"))}).ready, false);
const flat = {...model,manifestFiles:model.manifestFiles.map(f=>({...f,relativePath:f.relativePath.replace("/model/","/")}))};
assert.equal(editor.manifestState(flat).ready,true);
const payload = editor.editPayload(model,"soft-lighting","data:image/png;base64,fixture",7);
assert.equal(payload.reference_image,"data:image/png;base64,fixture");
assert.equal(payload.operation,"soft-lighting");
assert.equal(payload.package_path,prefix);
assert.equal(payload.seed,7);
assert.equal(Object.hasOwn(payload,"prompt"),false);
assert.throws(()=>editor.editPayload(model,"unsupported","",0));
assert.throws(()=>editor.editPayload({...model,id:"other"},"soft-lighting","",0));
for(const seed of [-1,2**32,NaN,1.5]) assert.throws(()=>editor.editPayload(model,"soft-lighting","",seed));
const manifest = editor.packagePayload(model);
assert.equal(manifest.manifest_files.length,10);
assert.equal(manifest.manifest_files[0].drive_file_id,"fixture-0");
editor.unmount();
console.log("2511 frontend contract: reference payload, presets, manifests and bounds PASS");
